/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SosRouteImport } from './routes/sos'
import { Route as AuthorityIndexRouteImport } from './routes/authority.index'
import { Route as AuthorityAnalyticsRouteImport } from './routes/authority.analytics'
import { Route as AuthorityVerificationsRouteImport } from './routes/authority.verifications'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as BusinessesIdRouteImport } from './routes/businesses.$id'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsIdRouteImport } from './routes/destinations.$id'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsIdRouteImport } from './routes/trips.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityIndexRoute = AuthorityIndexRouteImport.update({
  id: '/authority/',
  path: '/authority/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityAnalyticsRoute = AuthorityAnalyticsRouteImport.update({
  id: '/authority/analytics',
  path: '/authority/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityVerificationsRoute = AuthorityVerificationsRouteImport.update({
  id: '/authority/verifications',
  path: '/authority/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIdRoute = BusinessesIdRouteImport.update({
  id: '/businesses/$id',
  path: '/businesses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIdRoute = DestinationsIdRouteImport.update({
  id: '/destinations/$id',
  path: '/destinations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/bookings': typeof BookingsRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sos': typeof SosRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/verifications': typeof AuthorityVerificationsRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/authority/': typeof AuthorityIndexRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/bookings': typeof BookingsRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sos': typeof SosRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/verifications': typeof AuthorityVerificationsRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/authority': typeof AuthorityIndexRoute
  '/businesses': typeof BusinessesIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/bookings': typeof BookingsRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sos': typeof SosRoute
  '/authority/analytics': typeof AuthorityAnalyticsRoute
  '/authority/verifications': typeof AuthorityVerificationsRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/authority/': typeof AuthorityIndexRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/bookings'
    | '/guides'
    | '/login'
    | '/plan'
    | '/profile'
    | '/register'
    | '/report'
    | '/sos'
    | '/authority/analytics'
    | '/authority/verifications'
    | '/businesses/$id'
    | '/destinations/$id'
    | '/trips/$id'
    | '/authority/'
    | '/businesses/'
    | '/destinations/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/bookings'
    | '/guides'
    | '/login'
    | '/plan'
    | '/profile'
    | '/register'
    | '/report'
    | '/sos'
    | '/authority/analytics'
    | '/authority/verifications'
    | '/businesses/$id'
    | '/destinations/$id'
    | '/trips/$id'
    | '/authority'
    | '/businesses'
    | '/destinations'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/bookings'
    | '/guides'
    | '/login'
    | '/plan'
    | '/profile'
    | '/register'
    | '/report'
    | '/sos'
    | '/authority/analytics'
    | '/authority/verifications'
    | '/businesses/$id'
    | '/destinations/$id'
    | '/trips/$id'
    | '/authority/'
    | '/businesses/'
    | '/destinations/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  BookingsRoute: typeof BookingsRoute
  GuidesRoute: typeof GuidesRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  SosRoute: typeof SosRoute
  AuthorityAnalyticsRoute: typeof AuthorityAnalyticsRoute
  AuthorityVerificationsRoute: typeof AuthorityVerificationsRoute
  BusinessesIdRoute: typeof BusinessesIdRoute
  DestinationsIdRoute: typeof DestinationsIdRoute
  TripsIdRoute: typeof TripsIdRoute
  AuthorityIndexRoute: typeof AuthorityIndexRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/': {
      id: '/authority/'
      path: '/authority'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthorityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/analytics': {
      id: '/authority/analytics'
      path: '/authority/analytics'
      fullPath: '/authority/analytics'
      preLoaderRoute: typeof AuthorityAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/verifications': {
      id: '/authority/verifications'
      path: '/authority/verifications'
      fullPath: '/authority/verifications'
      preLoaderRoute: typeof AuthorityVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$id': {
      id: '/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof BusinessesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$id': {
      id: '/destinations/$id'
      path: '/destinations/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof DestinationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  BookingsRoute: BookingsRoute,
  GuidesRoute: GuidesRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  SosRoute: SosRoute,
  AuthorityAnalyticsRoute: AuthorityAnalyticsRoute,
  AuthorityVerificationsRoute: AuthorityVerificationsRoute,
  BusinessesIdRoute: BusinessesIdRoute,
  DestinationsIdRoute: DestinationsIdRoute,
  TripsIdRoute: TripsIdRoute,
  AuthorityIndexRoute: AuthorityIndexRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
