"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useParams } from "next/navigation";
import { RequireAuth } from "@/components/RequireAuth";
import { useAuth, isApiError } from "@/lib/auth-context";
import { api, type Trip, type Itinerary, type Destination } from "@/lib/api";
import { CalendarIcon, SparkleIcon } from "@/components/icons";

function ItineraryView({ itinerary }: { itinerary: Itinerary }) {
  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center justify-between text-sm text-foreground/60">
        <span>Version {itinerary.version}</span>
        <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
          Generated by {itinerary.generated_by}
        </span>
      </div>
      <ol className="relative flex flex-col gap-4 border-l border-border pl-5">
        {itinerary.items.map((item) => (
          <li key={item.id} className="relative">
            <span className="absolute -left-[26px] top-1.5 h-2.5 w-2.5 rounded-full bg-primary" />
            <div className="rounded-xl border border-border bg-surface p-4 text-sm">
              <div className="flex items-center justify-between gap-2">
                <span className="font-medium">{item.attraction_name ?? "Unnamed stop"}</span>
                {item.scheduled_time && (
                  <span className="whitespace-nowrap text-xs text-foreground/50">
                    {new Date(item.scheduled_time).toLocaleString(undefined, {
                      weekday: "short",
                      hour: "numeric",
                      minute: "2-digit",
                    })}
                  </span>
                )}
              </div>
              {item.explanation && <p className="mt-1.5 text-foreground/70">{item.explanation}</p>}
            </div>
          </li>
        ))}
      </ol>
    </div>
  );
}

function GenerateItineraryForm({
  tripId,
  destinations,
  onGenerated,
}: {
  tripId: string;
  destinations: Destination[];
  onGenerated: (it: Itinerary) => void;
}) {
  const { token } = useAuth();
  const [destinationId, setDestinationId] = useState(destinations[0]?.id ?? "");
  const [prompt, setPrompt] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (!token || !destinationId) return;
    setError(null);
    setSubmitting(true);
    try {
      const itinerary = await api.generateItinerary({ trip_id: tripId, destination_id: destinationId, prompt }, token);
      onGenerated(itinerary);
    } catch (err) {
      setError(isApiError(err) ? err.message : "Could not generate an itinerary.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={onSubmit} className="flex flex-col gap-3 rounded-2xl border border-border bg-surface p-5">
      <h2 className="flex items-center gap-1.5 text-sm font-medium">
        <SparkleIcon width={16} height={16} className="text-primary" />
        Generate an itinerary with AI
      </h2>
      <select
        value={destinationId}
        onChange={(e) => setDestinationId(e.target.value)}
        required
        className="rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40"
      >
        {destinations.map((d) => (
          <option key={d.id} value={d.id}>
            {d.name}
          </option>
        ))}
      </select>
      <textarea
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        required
        rows={2}
        placeholder="What are you looking for?"
        className="rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40"
      />
      {error && <p className="text-sm text-danger">{error}</p>}
      <button
        type="submit"
        disabled={submitting}
        className="self-start rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground hover:opacity-90 disabled:opacity-50"
      >
        {submitting ? "Planning…" : "Generate itinerary"}
      </button>
    </form>
  );
}

function ReplanForm({ itineraryId, onReplanned }: { itineraryId: string; onReplanned: (it: Itinerary) => void }) {
  const { token } = useAuth();
  const [reason, setReason] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (!token) return;
    setError(null);
    setSubmitting(true);
    try {
      const itinerary = await api.replanItinerary(itineraryId, { reason }, token);
      onReplanned(itinerary);
      setReason("");
    } catch (err) {
      setError(isApiError(err) ? err.message : "Could not replan.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={onSubmit} className="flex flex-col gap-2 rounded-2xl border border-border bg-surface-muted p-5">
      <h2 className="text-sm font-medium">Not quite right? Replan it</h2>
      <input
        value={reason}
        onChange={(e) => setReason(e.target.value)}
        required
        placeholder="e.g. It's raining, prefer indoor sights"
        className="rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40"
      />
      {error && <p className="text-sm text-danger">{error}</p>}
      <button
        type="submit"
        disabled={submitting}
        className="self-start rounded-full border border-border bg-surface px-4 py-2 text-sm font-medium hover:bg-surface-muted disabled:opacity-50"
      >
        {submitting ? "Replanning…" : "Replan"}
      </button>
    </form>
  );
}

function TripDetail() {
  const { token } = useAuth();
  const params = useParams<{ id: string }>();
  const tripId = params.id;
  const [trip, setTrip] = useState<Trip | null>(null);
  const [itinerary, setItinerary] = useState<Itinerary | null>(null);
  const [destinations, setDestinations] = useState<Destination[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!token || !tripId) return;
    Promise.all([
      api.getTrip(tripId, token),
      api.getTripItinerary(tripId, token).catch((err) => {
        if (isApiError(err) && err.status === 404) return null;
        throw err;
      }),
      api.listDestinations(),
    ])
      .then(([t, it, dests]) => {
        setTrip(t);
        setItinerary(it);
        setDestinations(dests);
      })
      .catch(() => setError("Could not load this trip."))
      .finally(() => setLoading(false));
  }, [token, tripId]);

  if (loading) return <p className="text-sm text-foreground/60">Loading…</p>;
  if (error || !trip) return <p className="text-sm text-danger">{error ?? "Trip not found."}</p>;

  return (
    <div className="mx-auto flex max-w-lg flex-col gap-6">
      <div className="flex items-start gap-3">
        <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">
          <CalendarIcon width={20} height={20} />
        </span>
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">{trip.title ?? "Untitled trip"}</h1>
          <p className="text-sm text-foreground/60">
            {trip.status}
            {trip.budget != null && ` · Budget: ${trip.currency} ${trip.budget}`}
          </p>
        </div>
      </div>

      {itinerary ? (
        <>
          <ItineraryView itinerary={itinerary} />
          <ReplanForm itineraryId={itinerary.id} onReplanned={setItinerary} />
        </>
      ) : (
        <GenerateItineraryForm tripId={trip.id} destinations={destinations} onGenerated={setItinerary} />
      )}
    </div>
  );
}

export default function TripDetailPage() {
  return (
    <RequireAuth>
      <TripDetail />
    </RequireAuth>
  );
}
