"""Travel domain models — `travel` schema (AI trip planning + safe-route
navigation, FR-02/FR-04). `ItineraryItem` uses the polymorphic reference
pattern confirmed in docs/00-planning/09-database-schema-plan.md §2 to
resolve the Revised-vs-Baseline field-list conflict: a nullable FK per
possible target type, only one populated per row, gated by `item_type`.
"""

import enum
import uuid
from datetime import datetime

from geoalchemy2 import Geography
from sqlalchemy import CheckConstraint, DateTime, Enum, ForeignKey, Numeric, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.db.mixins import TimestampMixin, UUIDPKMixin


class TripStatus(enum.StrEnum):
    DRAFT = "DRAFT"
    CONFIRMED = "CONFIRMED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ItemType(enum.StrEnum):
    ATTRACTION = "ATTRACTION"
    EVENT = "EVENT"
    ROUTE_SEGMENT = "ROUTE_SEGMENT"
    # HOTEL / RESTAURANT / TRANSPORT reference the `business`/`booking` schemas
    # (P1) — not modeled yet; item_type is reserved so no migration is needed
    # to add them later.
    HOTEL = "HOTEL"
    RESTAURANT = "RESTAURANT"
    TRANSPORT = "TRANSPORT"


class RouteMode(enum.StrEnum):
    SAFE = "SAFE"
    CROWD_FREE = "CROWD_FREE"
    ACCESSIBLE = "ACCESSIBLE"
    EMERGENCY = "EMERGENCY"
    FASTEST = "FASTEST"


class Trip(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "trips"
    __table_args__ = {"schema": "travel"}

    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("identity.users.id", ondelete="CASCADE"), nullable=False
    )
    title: Mapped[str | None] = mapped_column(String(200))
    start_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    end_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    budget: Mapped[float | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="INR")
    status: Mapped[TripStatus] = mapped_column(
        Enum(TripStatus, name="trip_status", schema="travel"), nullable=False, default=TripStatus.DRAFT
    )

    itineraries: Mapped[list["Itinerary"]] = relationship(back_populates="trip")


class Itinerary(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "itineraries"
    __table_args__ = {"schema": "travel"}

    trip_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("travel.trips.id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(nullable=False, default=1)
    generated_by: Mapped[str] = mapped_column(String(16), nullable=False, default="AI")  # AI|USER
    total_cost: Mapped[float | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="INR")

    trip: Mapped["Trip"] = relationship(back_populates="itineraries")
    items: Mapped[list["ItineraryItem"]] = relationship(
        back_populates="itinerary", order_by="ItineraryItem.sequence"
    )


class ItineraryItem(UUIDPKMixin, TimestampMixin, Base):
    __tablename__ = "itinerary_items"
    __table_args__ = (
        CheckConstraint("sequence >= 0", name="ck_itinerary_items_sequence_nonneg"),
        {"schema": "travel"},
    )

    itinerary_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("travel.itineraries.id", ondelete="CASCADE"), nullable=False
    )
    item_type: Mapped[ItemType] = mapped_column(
        Enum(ItemType, name="itinerary_item_type", schema="travel"), nullable=False
    )
    # Polymorphic target — exactly one of these is populated, matching item_type.
    attraction_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("tourism.attractions.id"))
    event_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("tourism.tourism_events.id"))
    route_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("travel.routes.id"))

    sequence: Mapped[int] = mapped_column(nullable=False)
    scheduled_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cost: Mapped[float | None] = mapped_column(Numeric(12, 2))
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="INR")
    transport_mode: Mapped[str | None] = mapped_column(String(32))

    # Explainability — Database Design extraction §5.2 "Reason snapshot".
    reason_code: Mapped[str | None] = mapped_column(String(64))
    explanation: Mapped[str | None]
    score_snapshot: Mapped[dict | None] = mapped_column(JSONB)

    itinerary: Mapped["Itinerary"] = relationship(back_populates="items")


class Route(UUIDPKMixin, TimestampMixin, Base):
    """Cached route computations. Geometry and scores come from the spatial
    routing engine (Phase 13) — never generated by the LLM
    (docs/00-planning/01-project-master-model.md §O)."""

    __tablename__ = "routes"
    __table_args__ = {"schema": "travel"}

    mode: Mapped[RouteMode] = mapped_column(Enum(RouteMode, name="route_mode", schema="travel"), nullable=False)
    origin: Mapped[str] = mapped_column(Geography(geometry_type="POINT", srid=4326), nullable=False)
    destination: Mapped[str] = mapped_column(Geography(geometry_type="POINT", srid=4326), nullable=False)
    geometry: Mapped[str | None] = mapped_column(Geography(geometry_type="LINESTRING", srid=4326))
    score: Mapped[float | None] = mapped_column(Numeric(6, 4))
    reasons: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    confidence: Mapped[float | None] = mapped_column(Numeric(4, 3))
    computed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    valid_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))