"""add gamification schema for P2 badges points challenges checkins

Revision ID: 13b3a822b473
Revises: 6ed7f205ad5c
Create Date: 2026-09-08 13:41:32.140665
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '13b3a822b473'
down_revision: str | None = '6ed7f205ad5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('EXPLORATION', 'HERITAGE', 'LOCAL_ECONOMY', 'RESPONSIBLE_TOURISM', 'COMMUNITY', name='gamification_category', schema='gamification'), nullable=False),
    sa.Column('icon_key', sa.String(length=64), nullable=False),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='gamification'
    )
    op.create_table('challenges',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('EXPLORATION', 'HERITAGE', 'LOCAL_ECONOMY', 'RESPONSIBLE_TOURISM', 'COMMUNITY', name='gamification_category', schema='gamification'), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['gamification.badges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='gamification'
    )
    op.create_table('destination_check_ins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gamification'
    )
    # idx_destination_check_ins_location is NOT created explicitly here —
    # GeoAlchemy2's Geography type auto-creates its own GIST index when the
    # table is created (see app/domains/tourism/models.py's note on this);
    # autogenerate renders it anyway since it looks like a diff, and running
    # it verbatim fails with "relation already exists" (documented gotcha,
    # backend/README.md's Migrations section).
    op.create_index('ix_destination_check_ins_user_destination', 'destination_check_ins', ['user_id', 'destination_id'], unique=False, schema='gamification')
    op.create_table('points_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('EXPLORATION', 'HERITAGE', 'LOCAL_ECONOMY', 'RESPONSIBLE_TOURISM', 'COMMUNITY', name='gamification_category', schema='gamification'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=32), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gamification'
    )
    op.create_index('ix_points_ledger_user_created', 'points_ledger', ['user_id', 'created_at'], unique=False, schema='gamification')
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('awarded_reason', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['gamification.badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gamification'
    )
    op.create_index('ix_user_badges_user_badge', 'user_badges', ['user_id', 'badge_id'], unique=True, schema='gamification')
    op.create_table('user_challenge_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('progress_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['gamification.challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gamification'
    )
    op.create_index('ix_user_challenge_progress_user_challenge', 'user_challenge_progress', ['user_id', 'challenge_id'], unique=True, schema='gamification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_challenge_progress_user_challenge', table_name='user_challenge_progress', schema='gamification')
    op.drop_table('user_challenge_progress', schema='gamification')
    op.drop_index('ix_user_badges_user_badge', table_name='user_badges', schema='gamification')
    op.drop_table('user_badges', schema='gamification')
    op.drop_index('ix_points_ledger_user_created', table_name='points_ledger', schema='gamification')
    op.drop_table('points_ledger', schema='gamification')
    op.drop_index('ix_destination_check_ins_user_destination', table_name='destination_check_ins', schema='gamification')
    # The GIST index on destination_check_ins.location is dropped automatically
    # with the table (GeoAlchemy2 auto-created it; there's no separate drop_index
    # for it above, matching upgrade()'s note).
    op.drop_table('destination_check_ins', schema='gamification')
    op.drop_table('challenges', schema='gamification')
    op.drop_table('badges', schema='gamification')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls above do not drop the
    # PostgreSQL ENUM type shared across badges/challenges/points_ledger
    # (a known autogenerate gap, documented in backend/README.md's
    # Migrations section) — without this, re-running upgrade() after a
    # downgrade fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS gamification.gamification_category")
