"""add location_sharing schema for live location sharing

Adds the `location_sharing` schema: `location_shares` (one row per
user-controlled share, current-location-state only — never a GPS history
log), `location_share_events` (append-only lifecycle audit, mirrors
`emergency.sos_events`), and `location_share_access_tokens` (mirrors
`identity.trusted_contact_access_tokens`, one token per share).

RLS is enabled on `location_shares` (owner-or-service only — no
authority-role branch, since authority access to location stays entirely
on the existing `emergency.sos_requests` path) and on
`location_share_access_tokens` (service-only, mirrors
`trusted_contact_tokens_service_only`), matching the
`_SERVICE_BYPASS`/`_CURRENT_USER`/`FORCE ROW LEVEL SECURITY` pattern from
b797776b9c1d_row_level_security_on_high_sensitivity_.py — including the
later `NULLIF(..., '')` cast fix from
91fa82c5074b_fix_rls_current_user_cast_to_tolerate_.py applied from the
start here, rather than repeating that bug. `location_share_events` gets
no RLS, matching `emergency.sos_events`.

Revision ID: 1f4979f98d26
Revises: 3dc196dec20f
Create Date: 2026-09-11 00:00:00.000000
"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f4979f98d26'
down_revision: str | None = '3dc196dec20f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SERVICE_BYPASS = "current_setting('app.user_role', true) IN ('service', 'authority_platform_admin')"
# NULLIF(..., '') before the cast — a pooled connection that has ever had
# app.current_user_id set reverts it to '' (not NULL) once that transaction
# ends, and casting ''::uuid raises rather than comparing false. Fixed for
# the original 5 RLS tables in 91fa82c5074b_fix_rls_current_user_cast_to_tolerate_.py;
# applying that same fix here from the start rather than repeating the bug.
_CURRENT_USER = "NULLIF(current_setting('app.current_user_id', true), '')::uuid"


def upgrade() -> None:
    # This repo's schemas are normally created via infra/postgres/init.sql
    # on a fresh volume, not by migrations. Against this project's real
    # (Supabase-hosted) database, the migration role lacks database-level
    # CREATE privilege, so `CREATE SCHEMA IF NOT EXISTS` here would itself
    # be denied even when the schema already exists — the schema and the
    # travindi_migrator/travindi_app grants on it were provisioned
    # out-of-band instead (same workaround this project's Supabase
    # migration already established for every other schema).

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_shares',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.Enum('TRUSTED_CONTACT', 'GROUP', name='recipient_type', schema='location_sharing'), nullable=False),
    sa.Column('trusted_contact_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=120), nullable=True),
    sa.Column('precision', sa.Enum('PRECISE', 'APPROXIMATE', name='share_precision', schema='location_sharing'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='share_status', schema='location_sharing'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trusted_contact_id'], ['identity.trusted_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['travel.trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='location_sharing'
    )
    # idx_location_shares_current_location is NOT created explicitly —
    # GeoAlchemy2's Geography type auto-creates its own GIST index
    # (documented gotcha, backend/README.md's Migrations section); running
    # it verbatim fails with "relation already exists".

    op.create_table('location_share_events',
    sa.Column('location_share_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_share_id'], ['location_sharing.location_shares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.users.id']),
    sa.PrimaryKeyConstraint('id'),
    schema='location_sharing'
    )

    op.create_table('location_share_access_tokens',
    sa.Column('location_share_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_share_id'], ['location_sharing.location_shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_share_id'),
    sa.UniqueConstraint('token_hash'),
    schema='location_sharing'
    )
    # ### end Alembic commands ###

    # --- RLS: location_shares (owner-or-service only, no authority branch) ---
    op.execute("ALTER TABLE location_sharing.location_shares ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE location_sharing.location_shares FORCE ROW LEVEL SECURITY")
    op.execute(f"""
        CREATE POLICY location_shares_owner_or_service ON location_sharing.location_shares
        USING ({_SERVICE_BYPASS} OR user_id = {_CURRENT_USER})
        WITH CHECK ({_SERVICE_BYPASS} OR user_id = {_CURRENT_USER})
    """)

    # --- RLS: location_share_access_tokens (service only, mirrors trusted_contact_tokens_service_only) ---
    op.execute("ALTER TABLE location_sharing.location_share_access_tokens ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE location_sharing.location_share_access_tokens FORCE ROW LEVEL SECURITY")
    op.execute(f"""
        CREATE POLICY location_share_tokens_service_only ON location_sharing.location_share_access_tokens
        USING ({_SERVICE_BYPASS})
        WITH CHECK ({_SERVICE_BYPASS})
    """)


def downgrade() -> None:
    op.execute(
        "DROP POLICY IF EXISTS location_share_tokens_service_only ON location_sharing.location_share_access_tokens"
    )
    op.execute("ALTER TABLE location_sharing.location_share_access_tokens NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE location_sharing.location_share_access_tokens DISABLE ROW LEVEL SECURITY")

    op.execute("DROP POLICY IF EXISTS location_shares_owner_or_service ON location_sharing.location_shares")
    op.execute("ALTER TABLE location_sharing.location_shares NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE location_sharing.location_shares DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_share_access_tokens', schema='location_sharing')
    op.drop_table('location_share_events', schema='location_sharing')
    # idx_location_shares_current_location's GIST index drops automatically with the table.
    op.drop_table('location_shares', schema='location_sharing')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls above do not drop the
    # PostgreSQL ENUM types created inline with each table (documented
    # gotcha, backend/README.md's Migrations section) — without this,
    # re-running upgrade() after a downgrade fails with "type already exists".
    for enum_name in ["share_status", "share_precision", "recipient_type"]:
        op.execute(f"DROP TYPE IF EXISTS location_sharing.{enum_name}")
