"""add group_travel schema for P2 shared trips group location and safety

Revision ID: 346dccbf1402
Revises: 3b8c60e4e10e
Create Date: 2026-09-08 14:51:23.820086
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '346dccbf1402'
down_revision: str | None = '3b8c60e4e10e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_members',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='trip_member_role', schema='group_travel'), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'LEFT', name='trip_member_status', schema='group_travel'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['travel.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='group_travel'
    )
    op.create_index('ix_trip_members_trip_user', 'trip_members', ['trip_id', 'user_id'], unique=True, schema='group_travel')
    op.create_table('trip_member_locations',
    sa.Column('trip_member_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['trip_member_id'], ['group_travel.trip_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_member_id'),
    schema='group_travel'
    )
    # idx_trip_member_locations_location is NOT created explicitly —
    # GeoAlchemy2's Geography type auto-creates its own GIST index
    # (documented gotcha, backend/README.md's Migrations section); running
    # it verbatim fails with "relation already exists".
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # idx_trip_member_locations_location's GIST index drops automatically with the table.
    op.drop_table('trip_member_locations', schema='group_travel')
    op.drop_index('ix_trip_members_trip_user', table_name='trip_members', schema='group_travel')
    op.drop_table('trip_members', schema='group_travel')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls above do not drop the
    # PostgreSQL ENUM types created inline with each table (documented
    # gotcha, backend/README.md's Migrations section) — without this,
    # re-running upgrade() after a downgrade fails with "type already exists".
    for enum_name in ["trip_member_status", "trip_member_role"]:
        op.execute(f"DROP TYPE IF EXISTS group_travel.{enum_name}")
