"""add financial schema for P2 expense tracking and receipt ocr

Revision ID: 3b8c60e4e10e
Revises: ae2d487d2e74
Create Date: 2026-09-08 14:31:15.414773
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8c60e4e10e'
down_revision: str | None = 'ae2d487d2e74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('ACCOMMODATION', 'FOOD', 'TRANSPORT', 'SHOPPING', 'ACTIVITIES', 'OTHER', name='expense_category', schema='financial'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'RECEIPT_SCAN', name='expense_source', schema='financial'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['travel.trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='financial'
    )
    op.create_index('ix_expenses_trip_incurred', 'expenses', ['trip_id', 'incurred_at'], unique=False, schema='financial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_trip_incurred', table_name='expenses', schema='financial')
    op.drop_table('expenses', schema='financial')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table does not drop the PostgreSQL ENUM
    # types created inline with the table (documented gotcha,
    # backend/README.md's Migrations section) — without this, re-running
    # upgrade() after a downgrade fails with "type already exists".
    for enum_name in ["expense_source", "expense_category"]:
        op.execute(f"DROP TYPE IF EXISTS financial.{enum_name}")
