"""initial P0 schema

Revision ID: 3c27907ea6bb
Revises: 
Create Date: 2026-09-07 06:26:04.458647
"""
from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c27907ea6bb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('h3_cell', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('retention_class', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='crowd'
    )
    op.create_index('ix_crowd_observations_h3_recorded', 'observations', ['h3_cell', 'recorded_at'], unique=False, schema='crowd')
    op.create_table('emergency_resources',
    sa.Column('resource_type', sa.Enum('POLICE', 'AMBULANCE', 'HOSPITAL', 'FIRE', name='emergency_resource_type', schema='emergency'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='emergency'
    )
    op.create_table('policies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='governance'
    )
    op.create_table('retention_rules',
    sa.Column('data_class', sa.String(length=64), nullable=False),
    sa.Column('retention_period_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_class'),
    schema='governance'
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='user_status', schema='identity'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    schema='identity'
    )
    op.create_table('ai_predictions',
    sa.Column('prediction_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('knowledge_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('approval_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('destinations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tourism'
    )
    op.create_table('routes',
    sa.Column('mode', sa.Enum('SAFE', 'CROWD_FREE', 'ACCESSIBLE', 'EMERGENCY', 'FASTEST', name='route_mode', schema='travel'), nullable=False),
    sa.Column('origin', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('destination', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='travel'
    )
    op.create_table('crowd_cells',
    sa.Column('h3_cell', sa.String(length=16), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=True),
    sa.Column('density', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('velocity', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crowd'
    )
    op.create_index('ix_crowd_cells_h3_observed', 'crowd_cells', ['h3_cell', 'observed_at'], unique=False, schema='crowd')
    op.create_table('crowd_events',
    sa.Column('event_type', sa.Enum('THRESHOLD_CROSSED', 'ANOMALY_DETECTED', name='crowd_event_type', schema='crowd'), nullable=False),
    sa.Column('h3_cell', sa.String(length=16), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crowd'
    )
    op.create_table('crowd_predictions',
    sa.Column('h3_cell', sa.String(length=16), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('predicted_for', sa.DateTime(), nullable=False),
    sa.Column('density', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crowd'
    )
    op.create_index('ix_crowd_predictions_h3_for', 'crowd_predictions', ['h3_cell', 'predicted_for'], unique=False, schema='crowd')
    op.create_table('iot_devices',
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('h3_cell', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crowd'
    )
    op.create_table('location_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('h3_cell', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('retention_class', sa.String(length=32), nullable=False),
    sa.Column('consent_basis', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='crowd'
    )
    op.create_table('sos_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACKNOWLEDGED', 'AUTHORITY_NOTIFIED', 'RESOURCE_ASSIGNED', 'RESPONDER_ARRIVED', 'RESOLVED', 'CANCELLED', 'FALSE_ALARM', name='sos_status', schema='emergency'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('emergency_type', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('local_ack_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='emergency'
    )
    op.create_index('ix_sos_requests_status_created', 'sos_requests', ['status', 'created_at'], unique=False, schema='emergency')
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SERVICE', name='audit_actor_type', schema='governance'), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='governance'
    )
    op.create_index('ix_audit_logs_correlation_id', 'audit_logs', ['correlation_id'], unique=False, schema='governance')
    op.create_table('trusted_contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('relationship_label', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('user_consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('user_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('push_token', sa.String(length=512), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=True),
    sa.Column('travel_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accessibility_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='identity'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.Enum('POLICE', 'EMERGENCY_RESPONDER', 'TOURISM_DEPT', 'MUNICIPALITY', 'VERIFIER', 'PLATFORM_ADMIN', name='authority_role', schema='identity'), nullable=False),
    sa.Column('assigned_geography', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('ai_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('knowledge_documents',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge.knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('recommendations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('incidents',
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED', 'FALSE_ALARM', name='incident_status', schema='safety'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_index('ix_incidents_status_created', 'incidents', ['status', 'created_at'], unique=False, schema='safety')
    op.create_table('risk_zones',
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('safe_zones',
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('safety_scores',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('attractions',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tourism'
    )
    op.create_table('facilities',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_type', sa.String(length=64), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tourism'
    )
    op.create_table('tourism_events',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tourism'
    )
    op.create_table('trips',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trip_status', schema='travel'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='travel'
    )
    op.create_table('iot_measurements',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('measurement_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['crowd.iot_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='crowd'
    )
    op.create_index('ix_iot_measurements_device_recorded', 'iot_measurements', ['device_id', 'recorded_at'], unique=False, schema='crowd')
    op.create_table('resource_assignments',
    sa.Column('sos_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['safety.incidents.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['emergency.emergency_resources.id'], ),
    sa.ForeignKeyConstraint(['sos_id'], ['emergency.sos_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='emergency'
    )
    op.create_table('sos_events',
    sa.Column('sos_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['sos_id'], ['emergency.sos_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='emergency'
    )
    op.create_table('trusted_contact_access_tokens',
    sa.Column('trusted_contact_id', sa.UUID(), nullable=False),
    sa.Column('sos_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('otp_verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sos_id'], ['emergency.sos_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trusted_contact_id'], ['identity.trusted_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='identity'
    )
    op.create_index('ix_trusted_contact_tokens_sos_id', 'trusted_contact_access_tokens', ['sos_id'], unique=False, schema='identity')
    op.create_table('ai_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', name='ai_message_role', schema='knowledge'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['knowledge.ai_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('knowledge_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge.knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('incident_events',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['safety.incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('incident_evidence',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['safety.incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_table('itineraries',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=16), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['travel.trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='travel'
    )
    op.create_table('ai_tool_calls',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['knowledge.ai_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge.knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge.knowledge_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='knowledge'
    )
    op.create_index('ix_knowledge_chunks_embedding', 'knowledge_chunks', ['embedding'], unique=False, schema='knowledge', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('itinerary_items',
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('ATTRACTION', 'EVENT', 'ROUTE_SEGMENT', 'HOTEL', 'RESTAURANT', 'TRANSPORT', name='itinerary_item_type', schema='travel'), nullable=False),
    sa.Column('attraction_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transport_mode', sa.String(length=32), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('score_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence >= 0', name='ck_itinerary_items_sequence_nonneg'),
    sa.ForeignKeyConstraint(['attraction_id'], ['tourism.attractions.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['tourism.tourism_events.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['travel.itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['travel.routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='travel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_items', schema='travel')
    op.drop_index('ix_knowledge_chunks_embedding', table_name='knowledge_chunks', schema='knowledge', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_chunks', schema='knowledge')
    op.drop_table('ai_tool_calls', schema='knowledge')
    op.drop_table('itineraries', schema='travel')
    op.drop_table('incident_evidence', schema='safety')
    op.drop_table('incident_events', schema='safety')
    op.drop_table('knowledge_versions', schema='knowledge')
    op.drop_table('ai_messages', schema='knowledge')
    op.drop_index('ix_trusted_contact_tokens_sos_id', table_name='trusted_contact_access_tokens', schema='identity')
    op.drop_table('trusted_contact_access_tokens', schema='identity')
    op.drop_table('sos_events', schema='emergency')
    op.drop_table('resource_assignments', schema='emergency')
    op.drop_index('ix_iot_measurements_device_recorded', table_name='iot_measurements', schema='crowd')
    op.drop_table('iot_measurements', schema='crowd')
    op.drop_table('trips', schema='travel')
    op.drop_table('tourism_events', schema='tourism')
    op.drop_table('facilities', schema='tourism')
    op.drop_table('attractions', schema='tourism')
    op.drop_table('safety_scores', schema='safety')
    op.drop_table('safe_zones', schema='safety')
    op.drop_table('risk_zones', schema='safety')
    op.drop_index('ix_incidents_status_created', table_name='incidents', schema='safety')
    op.drop_table('incidents', schema='safety')
    op.drop_table('recommendations', schema='knowledge')
    op.drop_table('knowledge_documents', schema='knowledge')
    op.drop_table('ai_sessions', schema='knowledge')
    op.drop_table('user_roles', schema='identity')
    op.drop_table('user_profiles', schema='identity')
    op.drop_table('user_devices', schema='identity')
    op.drop_table('user_consents', schema='identity')
    op.drop_table('trusted_contacts', schema='identity')
    op.drop_index('ix_audit_logs_correlation_id', table_name='audit_logs', schema='governance')
    op.drop_table('audit_logs', schema='governance')
    op.drop_index('ix_sos_requests_status_created', table_name='sos_requests', schema='emergency')
    op.drop_table('sos_requests', schema='emergency')
    op.drop_table('location_events', schema='crowd')
    op.drop_table('iot_devices', schema='crowd')
    op.drop_index('ix_crowd_predictions_h3_for', table_name='crowd_predictions', schema='crowd')
    op.drop_table('crowd_predictions', schema='crowd')
    op.drop_table('crowd_events', schema='crowd')
    op.drop_index('ix_crowd_cells_h3_observed', table_name='crowd_cells', schema='crowd')
    op.drop_table('crowd_cells', schema='crowd')
    op.drop_table('routes', schema='travel')
    op.drop_table('destinations', schema='tourism')
    op.drop_table('knowledge_sources', schema='knowledge')
    op.drop_table('ai_predictions', schema='knowledge')
    op.drop_table('users', schema='identity')
    op.drop_table('retention_rules', schema='governance')
    op.drop_table('policies', schema='governance')
    op.drop_table('emergency_resources', schema='emergency')
    op.drop_index('ix_crowd_observations_h3_recorded', table_name='observations', schema='crowd')
    op.drop_table('observations', schema='crowd')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls above do not drop the
    # PostgreSQL ENUM types created inline with each table (a known
    # autogenerate gap) — without this, re-running upgrade() after a
    # downgrade fails with "type already exists". Drop them explicitly.
    for enum_schema, enum_name in [
        ("identity", "user_status"),
        ("identity", "authority_role"),
        ("travel", "trip_status"),
        ("travel", "itinerary_item_type"),
        ("travel", "route_mode"),
        ("safety", "incident_status"),
        ("emergency", "sos_status"),
        ("emergency", "emergency_resource_type"),
        ("crowd", "crowd_event_type"),
        ("knowledge", "ai_message_role"),
        ("governance", "audit_actor_type"),
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_schema}.{enum_name}")
