"""add image_url to business profiles

Revision ID: 3dc196dec20f
Revises: fdbc466eb1c4
Create Date: 2026-09-10 22:32:57.880902
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3dc196dec20f'
down_revision: str | None = 'fdbc466eb1c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('image_url', sa.String(length=500), nullable=True), schema='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'image_url', schema='business')
    # ### end Alembic commands ###
