"""add booking schema for P1 bookings and tickets

Revision ID: 6ed7f205ad5c
Revises: b94e38113e8f
Create Date: 2026-09-08 08:03:57.971550
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ed7f205ad5c'
down_revision: str | None = 'b94e38113e8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('availability_id', sa.UUID(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', 'COMPLETED', name='booking_status', schema='booking'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['business.availability.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['business.services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='booking'
    )
    op.create_table('tickets',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'CHECKED_IN', 'VOID', name='ticket_status', schema='booking'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('qr_token'),
    schema='booking'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets', schema='booking')
    op.drop_table('bookings', schema='booking')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls above do not drop the
    # PostgreSQL ENUM types created inline with each table (a known
    # autogenerate gap) — without this, re-running upgrade() after a
    # downgrade fails with "type already exists". Drop them explicitly.
    for enum_schema, enum_name in [
        ("booking", "ticket_status"),
        ("booking", "booking_status"),
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_schema}.{enum_name}")
