"""add lost_found schema for P2 lost and found item reports and matches

Revision ID: ae2d487d2e74
Revises: 13b3a822b473
Create Date: 2026-09-08 14:11:12.540202
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ae2d487d2e74'
down_revision: str | None = '13b3a822b473'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_item_reports',
    sa.Column('finder_user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ELECTRONICS', 'DOCUMENTS', 'BAG_LUGGAGE', 'CLOTHING', 'JEWELRY', 'OTHER', name='lost_found_category', schema='lost_found'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('storage_location', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLAIMED', 'RETURNED', name='found_item_status', schema='lost_found'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.ForeignKeyConstraint(['finder_user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='lost_found'
    )
    # idx_found_item_reports_location is NOT created explicitly — GeoAlchemy2's
    # Geography type auto-creates its own GIST index (documented gotcha,
    # backend/README.md's Migrations section); running it verbatim fails with
    # "relation already exists".
    op.create_index('ix_found_item_reports_embedding', 'found_item_reports', ['embedding'], unique=False, schema='lost_found', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('lost_item_reports',
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ELECTRONICS', 'DOCUMENTS', 'BAG_LUGGAGE', 'CLOTHING', 'JEWELRY', 'OTHER', name='lost_found_category', schema='lost_found'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'MATCHED', 'RESOLVED', 'CLOSED', name='lost_item_status', schema='lost_found'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='lost_found'
    )
    # idx_lost_item_reports_location — same auto-created-GIST-index note as above.
    op.create_index('ix_lost_item_reports_embedding', 'lost_item_reports', ['embedding'], unique=False, schema='lost_found', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('lost_found_matches',
    sa.Column('lost_item_id', sa.UUID(), nullable=False),
    sa.Column('found_item_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'CONFIRMED', 'REJECTED', name='lost_found_match_status', schema='lost_found'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['lost_found.found_item_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_found.lost_item_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='lost_found'
    )
    op.create_index('ix_lost_found_matches_pair', 'lost_found_matches', ['lost_item_id', 'found_item_id'], unique=True, schema='lost_found')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lost_found_matches_pair', table_name='lost_found_matches', schema='lost_found')
    op.drop_table('lost_found_matches', schema='lost_found')
    op.drop_index('ix_lost_item_reports_embedding', table_name='lost_item_reports', schema='lost_found', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # idx_lost_item_reports_location's GIST index drops automatically with the table.
    op.drop_table('lost_item_reports', schema='lost_found')
    op.drop_index('ix_found_item_reports_embedding', table_name='found_item_reports', schema='lost_found', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # idx_found_item_reports_location's GIST index drops automatically with the table.
    op.drop_table('found_item_reports', schema='lost_found')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls above do not drop the
    # PostgreSQL ENUM types created inline with each table (documented
    # gotcha, backend/README.md's Migrations section) — without this,
    # re-running upgrade() after a downgrade fails with "type already exists".
    for enum_name in ["lost_found_match_status", "found_item_status", "lost_item_status", "lost_found_category"]:
        op.execute(f"DROP TYPE IF EXISTS lost_found.{enum_name}")
