"""add trust and business schemas for P1 verification reviews fraud and business directory

Revision ID: b94e38113e8f
Revises: 91fa82c5074b
Create Date: 2026-09-08 00:40:55.170269
"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b94e38113e8f'
down_revision: str | None = '91fa82c5074b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('HOTEL', 'RESTAURANT', 'TAXI', 'ARTISAN', 'TOUR_OPERATOR', 'OTHER', name='business_category', schema='business'), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='business'
    )
    op.create_table('guides',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='business'
    )
    op.create_table('fraud_cases',
    sa.Column('reported_by_user_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONFIRMED', 'DISMISSED', name='fraud_case_status', schema='trust'), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trust'
    )
    op.create_table('reviews',
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('DESTINATION', 'ATTRACTION', 'BUSINESS', 'GUIDE', name='review_target_type', schema='trust'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trust'
    )
    op.create_index('ix_reviews_target', 'reviews', ['target_type', 'target_id'], unique=False, schema='trust')
    op.create_table('verifications',
    sa.Column('subject_type', sa.Enum('BUSINESS', 'GUIDE', name='verification_subject_type', schema='trust'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verification_status', schema='trust'), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['identity.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trust'
    )
    op.create_index('ix_verifications_subject', 'verifications', ['subject_type', 'subject_id'], unique=False, schema='trust')
    op.create_table('business_profiles',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accessibility_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('women_friendly_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('family_friendly_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    schema='business'
    )
    op.create_table('services',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='business'
    )
    op.create_table('credentials',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Enum('BUSINESS', 'GUIDE', name='verification_subject_type', schema='trust'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('credential_type', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['trust.verifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trust'
    )
    op.create_table('fraud_evidence',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('added_by_user_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['identity.users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['trust.fraud_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trust'
    )
    op.create_table('fraud_signals',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['trust.fraud_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='trust'
    )
    op.create_table('review_analysis',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('authenticity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['trust.reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id'),
    schema='trust'
    )
    op.create_table('availability',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['business.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='business'
    )
    op.create_table('offers',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['business.services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='business'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers', schema='business')
    op.drop_table('availability', schema='business')
    op.drop_table('review_analysis', schema='trust')
    op.drop_table('fraud_signals', schema='trust')
    op.drop_table('fraud_evidence', schema='trust')
    op.drop_table('credentials', schema='trust')
    op.drop_table('services', schema='business')
    op.drop_table('business_profiles', schema='business')
    op.drop_index('ix_verifications_subject', table_name='verifications', schema='trust')
    op.drop_table('verifications', schema='trust')
    op.drop_index('ix_reviews_target', table_name='reviews', schema='trust')
    op.drop_table('reviews', schema='trust')
    op.drop_table('fraud_cases', schema='trust')
    op.drop_table('guides', schema='business')
    op.drop_table('businesses', schema='business')
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls above do not drop the
    # PostgreSQL ENUM types created inline with each table (a known
    # autogenerate gap) — without this, re-running upgrade() after a
    # downgrade fails with "type already exists". Drop them explicitly.
    for enum_schema, enum_name in [
        ("business", "business_category"),
        ("trust", "verification_subject_type"),
        ("trust", "verification_status"),
        ("trust", "review_target_type"),
        ("trust", "fraud_case_status"),
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_schema}.{enum_name}")
