"""add trip is_public flag and social schema for P2 destination discussions

Revision ID: be8b8c8ea5ac
Revises: 346dccbf1402
Create Date: 2026-09-08 15:20:28.807462
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8b8c8ea5ac'
down_revision: str | None = '346dccbf1402'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_discussion_posts',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id'], ['tourism.destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='social'
    )
    op.create_index('ix_destination_discussion_posts_destination_created', 'destination_discussion_posts', ['destination_id', 'created_at'], unique=False, schema='social')
    # server_default is required here (unlike a brand-new table's columns
    # elsewhere in this codebase) because `travel.trips` already has real
    # rows — a NOT NULL ADD COLUMN with no default would fail against them.
    op.add_column('trips', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='travel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_public', schema='travel')
    op.drop_index('ix_destination_discussion_posts_destination_created', table_name='destination_discussion_posts', schema='social')
    op.drop_table('destination_discussion_posts', schema='social')
    # ### end Alembic commands ###
