"""add image_url to tourism destinations

Revision ID: d0eb220434ed
Revises: ff1af5639def
Create Date: 2026-09-08 19:01:33.123624
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd0eb220434ed'
down_revision: str | None = 'ff1af5639def'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('image_url', sa.String(length=500), nullable=True), schema='tourism')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'image_url', schema='tourism')
    # ### end Alembic commands ###
