"""add food intelligence fields to business profiles

Revision ID: fdbc466eb1c4
Revises: d0eb220434ed
Create Date: 2026-09-08 19:19:57.303817
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdbc466eb1c4'
down_revision: str | None = 'd0eb220434ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default needed: business_profiles already has real rows (the
    # seeded demo businesses) — a plain client-side ORM `default=list` does
    # not backfill existing rows, and a bare NOT NULL add-column fails.
    op.add_column(
        'business_profiles',
        sa.Column(
            'cuisines', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")
        ),
        schema='business',
    )
    op.add_column(
        'business_profiles',
        sa.Column(
            'dietary_options',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        schema='business',
    )
    # add_column (unlike create_table) does not create a brand-new Enum
    # type on its own — must create it explicitly first.
    price_range_enum = postgresql.ENUM("BUDGET", "MODERATE", "PREMIUM", name="price_range", schema="business")
    price_range_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'business_profiles',
        sa.Column('price_range', sa.Enum('BUDGET', 'MODERATE', 'PREMIUM', name='price_range', schema='business'), nullable=True),
        schema='business',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'price_range', schema='business')
    op.drop_column('business_profiles', 'dietary_options', schema='business')
    op.drop_column('business_profiles', 'cuisines', schema='business')
    # ### end Alembic commands ###
    # GeoAlchemy2-style gotcha, but for a plain Enum: dropping the column
    # does not drop the Postgres ENUM type itself.
    op.execute("DROP TYPE IF EXISTS business.price_range")
