"""add business eco certification flag for P2 sustainability

Revision ID: ff1af5639def
Revises: be8b8c8ea5ac
Create Date: 2026-09-08 15:53:36.666046
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1af5639def'
down_revision: str | None = 'be8b8c8ea5ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required — business.businesses already has real rows
    # (same reasoning as the travel.trips.is_public migration).
    op.add_column('businesses', sa.Column('is_eco_certified', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='business')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'is_eco_certified', schema='business')
    # ### end Alembic commands ###
