import { destinations } from '@/data/destinations';
import { gatewayCities } from '@/data/gateways';
import { getState } from '@/data/states';
import type { GeoPoint } from '@/data/types';
import type { CabPlaceKind, TransportVehicleType } from '@/types/api';

/**
 * The sample transport network served by the development backend.
 *
 * Sample listings — operator names are fictional, and every schedule, fare,
 * seat count and journey time is illustrative. Metro networks, lines and
 * stations use real geography (a selection of stations, in line order), but
 * their fares and journey times are sample estimates. Nothing here is live.
 */

// Places ------------------------------------------------------------------------

export interface TransportHub {
  slug: string;
  name: string;
  state: string | null;
  coordinates: GeoPoint;
}

/** Listed destinations plus the gateway cities trips commonly start from. */
export const HUBS: TransportHub[] = [
  ...destinations.map((d) => ({ slug: d.slug, name: d.name, state: getState(d.state)?.name ?? null, coordinates: d.coordinates })),
  ...gatewayCities.map((g) => ({ slug: g.slug, name: g.name, state: getState(g.state)?.name ?? null, coordinates: g.coordinates })),
];

const hubsBySlug = new Map(HUBS.map((hub) => [hub.slug, hub]));

export const hubBySlug = (slug: string) => hubsBySlug.get(slug);

export const destinationIdFor = (slug: string) => `dst_${slug}`;

export function hubByDestinationId(destinationId: string) {
  return destinationId.startsWith('dst_') ? hubsBySlug.get(destinationId.slice(4)) : undefined;
}

export const AIRPORTS: Record<string, string> = {
  delhi: 'Indira Gandhi International Airport',
  mumbai: 'Chhatrapati Shivaji Maharaj International Airport',
  bengaluru: 'Kempegowda International Airport',
  chennai: 'Chennai International Airport',
  hyderabad: 'Rajiv Gandhi International Airport',
  kolkata: 'Netaji Subhas Chandra Bose International Airport',
  kochi: 'Cochin International Airport',
  goa: 'Goa International Airport, Dabolim',
  jaipur: 'Jaipur International Airport',
  varanasi: 'Lal Bahadur Shastri International Airport',
  amritsar: 'Sri Guru Ram Dass Jee International Airport',
  'leh-ladakh': 'Kushok Bakula Rimpochee Airport, Leh',
  udaipur: 'Maharana Pratap Airport, Udaipur',
  guwahati: 'Lokpriya Gopinath Bordoloi International Airport',
  'andaman-islands': 'Veer Savarkar International Airport',
  ahmedabad: 'Sardar Vallabhbhai Patel International Airport',
  bhubaneswar: 'Biju Patnaik International Airport',
  madurai: 'Madurai Airport',
  jodhpur: 'Jodhpur Airport',
  'ajanta-ellora': 'Chhatrapati Sambhajinagar Airport',
  khajuraho: 'Khajuraho Airport',
  'bodh-gaya': 'Gaya Airport',
};

export const BUS_STATIONS: Record<string, string> = {
  delhi: 'Kashmere Gate ISBT',
  agra: 'Idgah Bus Stand, Agra',
  jaipur: 'Sindhi Camp Bus Stand',
  rishikesh: 'Rishikesh ISBT',
  manali: 'Manali Bus Stand',
  'spiti-valley': 'Kaza Bus Stand',
  'valley-of-flowers': 'Govindghat',
  amritsar: 'Amritsar ISBT',
  varanasi: 'Varanasi Cantt Bus Station',
  'bodh-gaya': 'Bodh Gaya Bus Stand',
  udaipur: 'Udaipur City Bus Stand',
  jodhpur: 'Raika Bagh Bus Stand, Jodhpur',
  jaisalmer: 'Jaisalmer Bus Stand',
  ranthambore: 'Sawai Madhopur Bus Stand',
  ahmedabad: 'Geeta Mandir Bus Station',
  'rann-of-kutch': 'Bhuj Bus Station',
  gir: 'Sasan Gir Bus Stand',
  mumbai: 'Mumbai Central Bus Depot',
  goa: 'Panaji Kadamba Bus Stand',
  'ajanta-ellora': 'Central Bus Stand, Chhatrapati Sambhajinagar',
  lonar: 'Lonar Bus Stand',
  hampi: 'Hosapete Bus Stand',
  bengaluru: 'Kempegowda Bus Station, Majestic',
  mysuru: 'Mysuru Suburban Bus Stand',
  coorg: 'Madikeri Bus Stand',
  kochi: 'Vyttila Mobility Hub',
  munnar: 'Munnar Bus Stand',
  alappuzha: 'Alappuzha Bus Station',
  chennai: 'Koyambedu Mofussil Bus Terminus',
  mahabalipuram: 'Mamallapuram Bus Stand',
  puducherry: 'Puducherry New Bus Stand',
  madurai: 'Mattuthavani Bus Terminus',
  thanjavur: 'Thanjavur New Bus Stand',
  hyderabad: 'Mahatma Gandhi Bus Station (MGBS)',
  warangal: 'Hanamkonda Bus Station',
  gandikota: 'Jammalamadugu Bus Stand',
  kolkata: 'Esplanade Bus Terminus',
  bhubaneswar: 'Baramunda Bus Stand',
  'puri-konark': 'Puri Bus Stand',
  guwahati: 'ISBT Guwahati',
  meghalaya: 'Police Bazar, Shillong',
  kaziranga: 'Kohora, Kaziranga',
};

// Operators (fictional) ------------------------------------------------------------

export interface OperatorDef {
  id: string;
  name: string;
}

export const AIRLINES: OperatorDef[] = [
  { id: 'biz_air_saffron', name: 'Saffron Skyways' },
  { id: 'biz_air_monsoon', name: 'Monsoon Wings' },
  { id: 'biz_air_kestrel', name: 'Kestrel Regional' },
];

export const BUS_OPERATORS: OperatorDef[] = [
  { id: 'biz_bus_banyan', name: 'Banyan Coach Lines' },
  { id: 'biz_bus_starlight', name: 'Starlight Sleeper Coaches' },
  { id: 'biz_bus_ghatroad', name: 'Ghat Road Express' },
  { id: 'biz_bus_mangotree', name: 'Mango Tree Travels' },
];

// Routes -----------------------------------------------------------------------------

/** [place, place, departures a day in each direction]. */
export type FlightRoute = readonly [a: string, b: string, daily: number];

export const FLIGHT_ROUTES: FlightRoute[] = [
  ['delhi', 'mumbai', 6],
  ['delhi', 'bengaluru', 5],
  ['delhi', 'chennai', 4],
  ['delhi', 'hyderabad', 5],
  ['delhi', 'kolkata', 4],
  ['mumbai', 'bengaluru', 5],
  ['mumbai', 'chennai', 4],
  ['mumbai', 'hyderabad', 4],
  ['mumbai', 'kolkata', 3],
  ['bengaluru', 'chennai', 3],
  ['bengaluru', 'hyderabad', 4],
  ['bengaluru', 'kolkata', 3],
  ['chennai', 'hyderabad', 3],
  ['chennai', 'kolkata', 3],
  ['hyderabad', 'kolkata', 3],
  ['kochi', 'delhi', 2],
  ['kochi', 'mumbai', 3],
  ['kochi', 'bengaluru', 3],
  ['kochi', 'chennai', 2],
  ['kochi', 'hyderabad', 2],
  ['goa', 'delhi', 3],
  ['goa', 'mumbai', 3],
  ['goa', 'bengaluru', 3],
  ['goa', 'hyderabad', 2],
  ['goa', 'chennai', 2],
  ['goa', 'kolkata', 1],
  ['jaipur', 'delhi', 2],
  ['jaipur', 'mumbai', 3],
  ['jaipur', 'bengaluru', 2],
  ['jaipur', 'hyderabad', 2],
  ['jaipur', 'kolkata', 1],
  ['varanasi', 'delhi', 3],
  ['varanasi', 'mumbai', 2],
  ['varanasi', 'bengaluru', 2],
  ['varanasi', 'kolkata', 1],
  ['varanasi', 'hyderabad', 1],
  ['varanasi', 'khajuraho', 1],
  ['amritsar', 'delhi', 2],
  ['amritsar', 'mumbai', 1],
  ['leh-ladakh', 'delhi', 3],
  ['leh-ladakh', 'mumbai', 1],
  ['udaipur', 'delhi', 2],
  ['udaipur', 'mumbai', 2],
  ['udaipur', 'bengaluru', 1],
  ['guwahati', 'delhi', 3],
  ['guwahati', 'kolkata', 3],
  ['guwahati', 'bengaluru', 2],
  ['guwahati', 'mumbai', 1],
  ['andaman-islands', 'chennai', 3],
  ['andaman-islands', 'kolkata', 2],
  ['andaman-islands', 'delhi', 1],
  ['andaman-islands', 'bengaluru', 1],
  ['ahmedabad', 'delhi', 4],
  ['ahmedabad', 'mumbai', 3],
  ['ahmedabad', 'bengaluru', 3],
  ['ahmedabad', 'hyderabad', 2],
  ['ahmedabad', 'chennai', 2],
  ['ahmedabad', 'kolkata', 1],
  ['bhubaneswar', 'delhi', 3],
  ['bhubaneswar', 'kolkata', 2],
  ['bhubaneswar', 'bengaluru', 2],
  ['bhubaneswar', 'mumbai', 1],
  ['bhubaneswar', 'hyderabad', 1],
  ['madurai', 'chennai', 3],
  ['madurai', 'bengaluru', 2],
  ['madurai', 'mumbai', 1],
  ['jodhpur', 'delhi', 2],
  ['jodhpur', 'mumbai', 1],
  ['jodhpur', 'bengaluru', 1],
  ['ajanta-ellora', 'delhi', 1],
  ['ajanta-ellora', 'mumbai', 1],
  ['ajanta-ellora', 'hyderabad', 1],
  ['khajuraho', 'delhi', 1],
  ['bodh-gaya', 'delhi', 1],
  ['bodh-gaya', 'kolkata', 1],
];

export interface BusRouteOptions {
  /** Mountain roads: served by smaller coaches. */
  hill?: boolean;
  /** Typical journey time where distance alone misleads (mountain roads). */
  minutes?: number;
  /** Mountain passes are driven in daylight only. */
  daytime?: boolean;
  /** Months (1–12) the road is open; year-round when absent. */
  months?: number[];
}

export type BusRoute = readonly [a: string, b: string, daily: number, options?: BusRouteOptions];

const OPEN_SUMMER = [6, 7, 8, 9, 10];

export const BUS_ROUTES: BusRoute[] = [
  ['delhi', 'agra', 5],
  ['delhi', 'jaipur', 5],
  ['delhi', 'rishikesh', 4],
  ['delhi', 'manali', 3, { hill: true, minutes: 780 }],
  ['delhi', 'amritsar', 3],
  ['delhi', 'varanasi', 2],
  ['agra', 'jaipur', 3],
  ['jaipur', 'udaipur', 3],
  ['jaipur', 'jodhpur', 3],
  ['jaipur', 'ranthambore', 2],
  ['jodhpur', 'jaisalmer', 3],
  ['udaipur', 'jodhpur', 2],
  ['ahmedabad', 'udaipur', 3],
  ['ahmedabad', 'rann-of-kutch', 2],
  ['ahmedabad', 'gir', 1],
  ['mumbai', 'ahmedabad', 3],
  ['mumbai', 'goa', 4],
  ['mumbai', 'ajanta-ellora', 3],
  ['ajanta-ellora', 'lonar', 2],
  ['goa', 'hampi', 2],
  ['bengaluru', 'goa', 3],
  ['bengaluru', 'mysuru', 6],
  ['bengaluru', 'coorg', 3, { hill: true, minutes: 330 }],
  ['mysuru', 'coorg', 3, { hill: true, minutes: 180 }],
  ['bengaluru', 'hampi', 3],
  ['bengaluru', 'kochi', 3],
  ['bengaluru', 'chennai', 5],
  ['bengaluru', 'hyderabad', 4],
  ['bengaluru', 'madurai', 2],
  ['bengaluru', 'puducherry', 2],
  ['chennai', 'mahabalipuram', 4],
  ['chennai', 'puducherry', 4],
  ['chennai', 'madurai', 3],
  ['chennai', 'thanjavur', 3],
  ['madurai', 'thanjavur', 3],
  ['madurai', 'munnar', 2, { hill: true, minutes: 300 }],
  ['kochi', 'munnar', 4, { hill: true, minutes: 270 }],
  ['kochi', 'alappuzha', 6],
  ['mahabalipuram', 'puducherry', 3],
  ['hyderabad', 'warangal', 5],
  ['hyderabad', 'gandikota', 1],
  ['varanasi', 'bodh-gaya', 2],
  ['kolkata', 'puri-konark', 2],
  ['bhubaneswar', 'puri-konark', 5],
  ['guwahati', 'meghalaya', 4, { hill: true, minutes: 210 }],
  ['guwahati', 'kaziranga', 3],
  ['manali', 'spiti-valley', 1, { hill: true, minutes: 540, daytime: true, months: OPEN_SUMMER }],
  ['rishikesh', 'valley-of-flowers', 1, { hill: true, minutes: 600, daytime: true, months: OPEN_SUMMER }],
];

// Metro -------------------------------------------------------------------------------

export interface MetroLineDef {
  id: string;
  name: string;
  colour: string;
  /** Stations in line order, with approximate kilometres from the first listed station. */
  stops: ReadonlyArray<readonly [stationId: string, km: number]>;
}

export interface MetroNetworkDef {
  id: string;
  name: string;
  city: string;
  /** Destination or gateway slug. */
  slug: string;
  coverage: 'full' | 'partial';
  stations: Record<string, string>;
  lines: MetroLineDef[];
  /** Distance slabs: [up to km, fare in rupees]. The last slab covers everything beyond. */
  fares: ReadonlyArray<readonly [upToKm: number, rupees: number]>;
}

export const METRO_NETWORKS: MetroNetworkDef[] = [
  {
    id: 'metro_delhi',
    name: 'Delhi Metro',
    city: 'Delhi',
    slug: 'delhi',
    coverage: 'partial',
    stations: {
      'samaypur-badli': 'Samaypur Badli',
      azadpur: 'Azadpur',
      vishwavidyalaya: 'Vishwavidyalaya',
      'kashmere-gate': 'Kashmere Gate',
      'chandni-chowk': 'Chandni Chowk',
      'new-delhi': 'New Delhi',
      'rajiv-chowk': 'Rajiv Chowk',
      'central-secretariat': 'Central Secretariat',
      ina: 'INA',
      aiims: 'AIIMS',
      'hauz-khas': 'Hauz Khas',
      saket: 'Saket',
      'qutab-minar': 'Qutab Minar',
      sikanderpur: 'Sikanderpur',
      'mg-road-gurugram': 'MG Road',
      'millennium-city-centre': 'Millennium City Centre Gurugram',
      'dwarka-sector-21': 'Dwarka Sector 21',
      'janakpuri-west': 'Janakpuri West',
      'rajouri-garden': 'Rajouri Garden',
      'kirti-nagar': 'Kirti Nagar',
      'karol-bagh': 'Karol Bagh',
      'mandi-house': 'Mandi House',
      indraprastha: 'Indraprastha',
      'yamuna-bank': 'Yamuna Bank',
      akshardham: 'Akshardham',
      'mayur-vihar-1': 'Mayur Vihar-I',
      'botanical-garden': 'Botanical Garden',
      'noida-city-centre': 'Noida City Centre',
      'lal-qila': 'Lal Qila',
      'jama-masjid': 'Jama Masjid',
      'delhi-gate': 'Delhi Gate',
      ito: 'ITO',
      janpath: 'Janpath',
      'khan-market': 'Khan Market',
      'lajpat-nagar': 'Lajpat Nagar',
      'nehru-place': 'Nehru Place',
      'kalkaji-mandir': 'Kalkaji Mandir',
      'badarpur-border': 'Badarpur Border',
      'terminal-1-igi-airport': 'Terminal 1-IGI Airport',
      'majlis-park': 'Majlis Park',
      'netaji-subhash-place': 'Netaji Subhash Place',
      'south-campus': 'Durgabai Deshmukh South Campus',
      'sarai-kale-khan-nizamuddin': 'Sarai Kale Khan-Nizamuddin',
      'anand-vihar-isbt': 'Anand Vihar ISBT',
      'shivaji-stadium': 'Shivaji Stadium',
      'dhaula-kuan': 'Dhaula Kuan',
      'delhi-aerocity': 'Delhi Aerocity',
      'igi-airport-t3': 'IGI Airport (Terminal 3)',
      'yashobhoomi-dwarka-sector-25': 'Yashobhoomi Dwarka Sector 25',
    },
    lines: [
      {
        id: 'yellow',
        name: 'Yellow Line',
        colour: '#E8B400',
        stops: [
          ['samaypur-badli', 0],
          ['azadpur', 8.6],
          ['vishwavidyalaya', 12.4],
          ['kashmere-gate', 15.1],
          ['chandni-chowk', 16.2],
          ['new-delhi', 18.4],
          ['rajiv-chowk', 19.5],
          ['central-secretariat', 21.9],
          ['ina', 25.4],
          ['aiims', 26.4],
          ['hauz-khas', 28.9],
          ['saket', 31.9],
          ['qutab-minar', 33.6],
          ['sikanderpur', 43.4],
          ['mg-road-gurugram', 44.6],
          ['millennium-city-centre', 49],
        ],
      },
      {
        id: 'blue',
        name: 'Blue Line',
        colour: '#1E6FD9',
        stops: [
          ['dwarka-sector-21', 0],
          ['janakpuri-west', 10.5],
          ['rajouri-garden', 15],
          ['kirti-nagar', 18.1],
          ['karol-bagh', 21.5],
          ['rajiv-chowk', 25],
          ['mandi-house', 27.2],
          ['indraprastha', 29.1],
          ['yamuna-bank', 31],
          ['akshardham', 33],
          ['mayur-vihar-1', 34.4],
          ['botanical-garden', 42.5],
          ['noida-city-centre', 45.5],
        ],
      },
      {
        id: 'violet',
        name: 'Violet Line',
        colour: '#7B3FA0',
        stops: [
          ['kashmere-gate', 0],
          ['lal-qila', 1.5],
          ['jama-masjid', 2.5],
          ['delhi-gate', 3.7],
          ['ito', 5],
          ['mandi-house', 6.1],
          ['janpath', 7.5],
          ['central-secretariat', 8.3],
          ['khan-market', 10.1],
          ['lajpat-nagar', 14],
          ['nehru-place', 17.3],
          ['kalkaji-mandir', 18.4],
          ['badarpur-border', 26.5],
        ],
      },
      {
        id: 'magenta',
        name: 'Magenta Line',
        colour: '#B0307A',
        stops: [
          ['janakpuri-west', 0],
          ['terminal-1-igi-airport', 7.8],
          ['hauz-khas', 17.9],
          ['kalkaji-mandir', 22.4],
          ['botanical-garden', 38.2],
        ],
      },
      {
        id: 'pink',
        name: 'Pink Line',
        colour: '#D9508A',
        stops: [
          ['majlis-park', 0],
          ['azadpur', 1.5],
          ['netaji-subhash-place', 4.9],
          ['rajouri-garden', 11.4],
          ['south-campus', 19.2],
          ['ina', 24.8],
          ['lajpat-nagar', 27.5],
          ['sarai-kale-khan-nizamuddin', 30.4],
          ['mayur-vihar-1', 32.7],
          ['anand-vihar-isbt', 38.5],
        ],
      },
      {
        id: 'airport-express',
        name: 'Airport Express Line',
        colour: '#E67E22',
        stops: [
          ['new-delhi', 0],
          ['shivaji-stadium', 1.9],
          ['dhaula-kuan', 8],
          ['delhi-aerocity', 14.4],
          ['igi-airport-t3', 18.4],
          ['dwarka-sector-21', 21.6],
          ['yashobhoomi-dwarka-sector-25', 23.4],
        ],
      },
    ],
    fares: [
      [2, 11],
      [5, 21],
      [12, 32],
      [21, 43],
      [32, 54],
      [Infinity, 64],
    ],
  },
  {
    id: 'metro_bengaluru',
    name: 'Namma Metro',
    city: 'Bengaluru',
    slug: 'bengaluru',
    coverage: 'partial',
    stations: {
      whitefield: 'Whitefield (Kadugodi)',
      krishnarajapura: 'Krishnarajapura',
      baiyappanahalli: 'Baiyappanahalli',
      indiranagar: 'Indiranagar',
      'mg-road': 'Mahatma Gandhi Road',
      'cubbon-park': 'Cubbon Park',
      'vidhana-soudha': 'Dr. B.R. Ambedkar Station (Vidhana Soudha)',
      majestic: 'Nadaprabhu Kempegowda Station, Majestic',
      'city-railway-station': 'Krantivira Sangolli Rayanna Railway Station',
      vijayanagar: 'Vijayanagar',
      'mysuru-road': 'Mysuru Road',
      kengeri: 'Kengeri',
      challaghatta: 'Challaghatta',
      nagasandra: 'Nagasandra',
      yeshwanthpur: 'Yeshwanthpur',
      rajajinagar: 'Rajajinagar',
      'sampige-road': 'Mantri Square Sampige Road',
      chickpete: 'Chickpete',
      'kr-market': 'Krishna Rajendra Market',
      lalbagh: 'Lalbagh',
      jayanagar: 'Jayanagar',
      'rv-road': 'Rashtreeya Vidyalaya Road',
      banashankari: 'Banashankari',
      'silk-institute': 'Silk Institute',
      'jayadeva-hospital': 'Jayadeva Hospital',
      'central-silk-board': 'Central Silk Board',
      'electronic-city': 'Electronic City',
      bommasandra: 'Bommasandra',
    },
    lines: [
      {
        id: 'purple',
        name: 'Purple Line',
        colour: '#8E44AD',
        stops: [
          ['whitefield', 0],
          ['krishnarajapura', 9.2],
          ['baiyappanahalli', 14.5],
          ['indiranagar', 17.6],
          ['mg-road', 20.3],
          ['cubbon-park', 21.5],
          ['vidhana-soudha', 22.4],
          ['majestic', 24.2],
          ['city-railway-station', 25.1],
          ['vijayanagar', 29],
          ['mysuru-road', 32.3],
          ['kengeri', 38.4],
          ['challaghatta', 41.9],
        ],
      },
      {
        id: 'green',
        name: 'Green Line',
        colour: '#27AE60',
        stops: [
          ['nagasandra', 0],
          ['yeshwanthpur', 5.9],
          ['rajajinagar', 8.6],
          ['sampige-road', 11.2],
          ['majestic', 12.4],
          ['chickpete', 13.4],
          ['kr-market', 14.4],
          ['lalbagh', 16.4],
          ['jayanagar', 18.8],
          ['rv-road', 19.9],
          ['banashankari', 21],
          ['silk-institute', 30.3],
        ],
      },
      {
        id: 'yellow',
        name: 'Yellow Line',
        colour: '#D4AC0D',
        stops: [
          ['rv-road', 0],
          ['jayadeva-hospital', 2],
          ['central-silk-board', 4.2],
          ['electronic-city', 13],
          ['bommasandra', 19.1],
        ],
      },
    ],
    fares: [
      [2, 10],
      [4, 20],
      [6, 30],
      [8, 40],
      [10, 50],
      [15, 60],
      [20, 70],
      [25, 80],
      [Infinity, 90],
    ],
  },
  {
    id: 'metro_mumbai',
    name: 'Mumbai Metro',
    city: 'Mumbai',
    slug: 'mumbai',
    coverage: 'partial',
    stations: {
      versova: 'Versova',
      'dn-nagar': 'D.N. Nagar',
      'azad-nagar': 'Azad Nagar',
      andheri: 'Andheri',
      weh: 'Western Express Highway',
      chakala: 'Chakala (J.B. Nagar)',
      'airport-road': 'Airport Road',
      'marol-naka': 'Marol Naka',
      'saki-naka': 'Saki Naka',
      asalpha: 'Asalpha',
      'jagruti-nagar': 'Jagruti Nagar',
      ghatkopar: 'Ghatkopar',
      'aarey-jvlr': 'Aarey JVLR',
      seepz: 'SEEPZ',
      'csmia-t2': 'Airport Terminal 2 (CSMIA T2)',
      'csmia-t1': 'Airport Terminal 1 (CSMIA T1)',
      bkc: 'Bandra-Kurla Complex',
      dadar: 'Dadar',
      siddhivinayak: 'Siddhivinayak',
      worli: 'Worli',
      mahalaxmi: 'Mahalaxmi',
      'mumbai-central': 'Mumbai Central',
      'grant-road': 'Grant Road',
      csmt: 'CSMT',
      churchgate: 'Churchgate',
      'cuffe-parade': 'Cuffe Parade',
    },
    lines: [
      {
        id: 'line-1',
        name: 'Line 1',
        colour: '#1F74C4',
        stops: [
          ['versova', 0],
          ['dn-nagar', 1.1],
          ['azad-nagar', 1.9],
          ['andheri', 3.2],
          ['weh', 4.3],
          ['chakala', 5.3],
          ['airport-road', 6.1],
          ['marol-naka', 7.1],
          ['saki-naka', 8.1],
          ['asalpha', 9.4],
          ['jagruti-nagar', 10.5],
          ['ghatkopar', 11.4],
        ],
      },
      {
        id: 'line-3',
        name: 'Line 3 (Aqua Line)',
        colour: '#1FA2B0',
        stops: [
          ['aarey-jvlr', 0],
          ['seepz', 1.4],
          ['marol-naka', 4],
          ['csmia-t2', 5.3],
          ['csmia-t1', 8.1],
          ['bkc', 12.1],
          ['dadar', 17],
          ['siddhivinayak', 18.2],
          ['worli', 19.9],
          ['mahalaxmi', 23.6],
          ['mumbai-central', 24.8],
          ['grant-road', 26.1],
          ['csmt', 29.4],
          ['churchgate', 31.1],
          ['cuffe-parade', 33.5],
        ],
      },
    ],
    fares: [
      [3, 10],
      [12, 20],
      [18, 30],
      [24, 40],
      [30, 50],
      [36, 60],
      [Infinity, 70],
    ],
  },
  {
    id: 'metro_hyderabad',
    name: 'Hyderabad Metro Rail',
    city: 'Hyderabad',
    slug: 'hyderabad',
    coverage: 'partial',
    stations: {
      miyapur: 'Miyapur',
      kukatpally: 'Kukatpally',
      balanagar: 'Dr. B.R. Ambedkar Balanagar',
      erragadda: 'Erragadda',
      ameerpet: 'Ameerpet',
      punjagutta: 'Punjagutta',
      khairatabad: 'Khairatabad',
      lakdikapul: 'Lakdikapul',
      assembly: 'Assembly',
      nampally: 'Nampally',
      'mg-bus-station': 'MG Bus Station',
      dilsukhnagar: 'Dilsukhnagar',
      'lb-nagar': 'L.B. Nagar',
      nagole: 'Nagole',
      uppal: 'Uppal',
      tarnaka: 'Tarnaka',
      'secunderabad-east': 'Secunderabad East',
      'parade-ground': 'Parade Ground',
      paradise: 'Paradise',
      begumpet: 'Begumpet',
      'jubilee-hills-check-post': 'Jubilee Hills Check Post',
      madhapur: 'Madhapur',
      'hitec-city': 'HITEC City',
      raidurg: 'Raidurg',
      'secunderabad-west': 'Secunderabad West',
      musheerabad: 'Musheerabad',
      'rtc-cross-roads': 'RTC Cross Roads',
      narayanaguda: 'Narayanaguda',
      'sultan-bazaar': 'Sultan Bazaar',
    },
    lines: [
      {
        id: 'red',
        name: 'Red Line',
        colour: '#D6453D',
        stops: [
          ['miyapur', 0],
          ['kukatpally', 4.8],
          ['balanagar', 7.6],
          ['erragadda', 10.1],
          ['ameerpet', 12.9],
          ['punjagutta', 14.1],
          ['khairatabad', 15.4],
          ['lakdikapul', 16.3],
          ['assembly', 17.3],
          ['nampally', 18.1],
          ['mg-bus-station', 20.5],
          ['dilsukhnagar', 25.4],
          ['lb-nagar', 29],
        ],
      },
      {
        id: 'blue',
        name: 'Blue Line',
        colour: '#2E86C1',
        stops: [
          ['nagole', 0],
          ['uppal', 1.5],
          ['tarnaka', 6.5],
          ['secunderabad-east', 9.6],
          ['parade-ground', 10.8],
          ['paradise', 11.9],
          ['begumpet', 14],
          ['ameerpet', 16],
          ['jubilee-hills-check-post', 20.1],
          ['madhapur', 22.1],
          ['hitec-city', 24.3],
          ['raidurg', 27],
        ],
      },
      {
        id: 'green',
        name: 'Green Line',
        colour: '#27AE60',
        stops: [
          ['parade-ground', 0],
          ['secunderabad-west', 1.4],
          ['musheerabad', 3.8],
          ['rtc-cross-roads', 5.1],
          ['narayanaguda', 7.2],
          ['sultan-bazaar', 8.6],
          ['mg-bus-station', 10],
        ],
      },
    ],
    fares: [
      [2, 12],
      [4, 18],
      [6, 30],
      [9, 40],
      [12, 50],
      [15, 55],
      [18, 60],
      [21, 66],
      [24, 70],
      [Infinity, 75],
    ],
  },
  {
    id: 'metro_chennai',
    name: 'Chennai Metro Rail',
    city: 'Chennai',
    slug: 'chennai',
    coverage: 'partial',
    stations: {
      'wimco-nagar-depot': 'Wimco Nagar Depot',
      tiruvottriyur: 'Tiruvottriyur',
      washermanpet: 'Washermanpet',
      mannadi: 'Mannadi',
      'high-court': 'High Court',
      'chennai-central': 'Chennai Central',
      'government-estate': 'Government Estate',
      lic: 'LIC',
      'thousand-lights': 'Thousand Lights',
      teynampet: 'Teynampet',
      saidapet: 'Saidapet',
      guindy: 'Guindy',
      alandur: 'Alandur',
      'chennai-airport': 'Chennai International Airport',
      egmore: 'Egmore',
      kilpauk: 'Kilpauk Medical College',
      'anna-nagar-tower': 'Anna Nagar Tower',
      thirumangalam: 'Thirumangalam',
      koyambedu: 'Koyambedu',
      cmbt: 'CMBT',
      vadapalani: 'Vadapalani',
      'ashok-nagar': 'Ashok Nagar',
      'st-thomas-mount': 'St. Thomas Mount',
    },
    lines: [
      {
        id: 'blue',
        name: 'Blue Line',
        colour: '#1F77D0',
        stops: [
          ['wimco-nagar-depot', 0],
          ['tiruvottriyur', 2.6],
          ['washermanpet', 9.1],
          ['mannadi', 10.6],
          ['high-court', 11.5],
          ['chennai-central', 12.6],
          ['government-estate', 14],
          ['lic', 15],
          ['thousand-lights', 16.2],
          ['teynampet', 18.3],
          ['saidapet', 21.9],
          ['guindy', 24.4],
          ['alandur', 26],
          ['chennai-airport', 32],
        ],
      },
      {
        id: 'green',
        name: 'Green Line',
        colour: '#2E9E4F',
        stops: [
          ['chennai-central', 0],
          ['egmore', 1.4],
          ['kilpauk', 4],
          ['anna-nagar-tower', 8.3],
          ['thirumangalam', 9.6],
          ['koyambedu', 11],
          ['cmbt', 12.1],
          ['vadapalani', 14.5],
          ['ashok-nagar', 16.4],
          ['alandur', 19.5],
          ['st-thomas-mount', 22],
        ],
      },
    ],
    fares: [
      [2, 10],
      [5, 20],
      [12, 30],
      [21, 40],
      [Infinity, 50],
    ],
  },
  {
    id: 'metro_kolkata',
    name: 'Kolkata Metro',
    city: 'Kolkata',
    slug: 'kolkata',
    coverage: 'partial',
    stations: {
      dakshineswar: 'Dakshineswar',
      'dum-dum': 'Dum Dum',
      shyambazar: 'Shyambazar',
      'girish-park': 'Girish Park',
      central: 'Central',
      esplanade: 'Esplanade',
      'park-street': 'Park Street',
      maidan: 'Maidan',
      'rabindra-sadan': 'Rabindra Sadan',
      kalighat: 'Kalighat',
      'mahanayak-uttam-kumar': 'Mahanayak Uttam Kumar',
      'shahid-khudiram': 'Shahid Khudiram',
      'howrah-maidan': 'Howrah Maidan',
      howrah: 'Howrah',
      mahakaran: 'Mahakaran',
      sealdah: 'Sealdah',
      phoolbagan: 'Phoolbagan',
      'salt-lake-stadium': 'Salt Lake Stadium',
      'city-centre': 'City Centre',
      karunamoyee: 'Karunamoyee',
      'salt-lake-sector-v': 'Salt Lake Sector V',
    },
    lines: [
      {
        id: 'blue',
        name: 'Blue Line',
        colour: '#1B5FAA',
        stops: [
          ['dakshineswar', 0],
          ['dum-dum', 4.9],
          ['shyambazar', 7.9],
          ['girish-park', 10],
          ['central', 11.6],
          ['esplanade', 13],
          ['park-street', 14.3],
          ['maidan', 15.2],
          ['rabindra-sadan', 16.3],
          ['kalighat', 18.4],
          ['mahanayak-uttam-kumar', 20.6],
          ['shahid-khudiram', 30.3],
        ],
      },
      {
        id: 'green',
        name: 'Green Line',
        colour: '#1E9A4C',
        stops: [
          ['howrah-maidan', 0],
          ['howrah', 1.2],
          ['mahakaran', 2.8],
          ['esplanade', 4.1],
          ['sealdah', 6.6],
          ['phoolbagan', 8.4],
          ['salt-lake-stadium', 9.5],
          ['city-centre', 11.6],
          ['karunamoyee', 13.7],
          ['salt-lake-sector-v', 16.5],
        ],
      },
    ],
    fares: [
      [2, 5],
      [5, 10],
      [10, 15],
      [20, 20],
      [30, 25],
      [Infinity, 30],
    ],
  },
  {
    id: 'metro_kochi',
    name: 'Kochi Metro',
    city: 'Kochi',
    slug: 'kochi',
    coverage: 'partial',
    stations: {
      aluva: 'Aluva',
      kalamassery: 'Kalamassery',
      'cochin-university': 'Cochin University',
      edapally: 'Edapally',
      palarivattom: 'Palarivattom',
      'jln-stadium': 'JLN Stadium',
      kaloor: 'Kaloor',
      'town-hall': 'Town Hall',
      'mg-road': 'M.G. Road',
      'maharajas-college': 'Maharaja’s College',
      'ernakulam-south': 'Ernakulam South',
      kadavanthra: 'Kadavanthra',
      vyttila: 'Vyttila',
      petta: 'Petta',
      thrippunithura: 'Thrippunithura',
    },
    lines: [
      {
        id: 'line-1',
        name: 'Line 1',
        colour: '#139CA8',
        stops: [
          ['aluva', 0],
          ['kalamassery', 7.7],
          ['cochin-university', 9],
          ['edapally', 12],
          ['palarivattom', 14.4],
          ['jln-stadium', 15.6],
          ['kaloor', 16.6],
          ['town-hall', 17.4],
          ['mg-road', 18.4],
          ['maharajas-college', 19.5],
          ['ernakulam-south', 20.6],
          ['kadavanthra', 21.6],
          ['vyttila', 23.8],
          ['petta', 25.8],
          ['thrippunithura', 28.1],
        ],
      },
    ],
    fares: [
      [2, 10],
      [5, 20],
      [12, 30],
      [19, 40],
      [24, 50],
      [Infinity, 60],
    ],
  },
  {
    id: 'metro_jaipur',
    name: 'Jaipur Metro',
    city: 'Jaipur',
    slug: 'jaipur',
    coverage: 'full',
    stations: {
      mansarovar: 'Mansarovar',
      'new-aatish-market': 'New Aatish Market',
      'vivek-vihar': 'Vivek Vihar',
      'shyam-nagar': 'Shyam Nagar',
      'ram-nagar': 'Ram Nagar',
      'civil-lines': 'Civil Lines',
      'railway-station': 'Railway Station',
      'sindhi-camp': 'Sindhi Camp',
      chandpole: 'Chandpole',
      'chhoti-chaupar': 'Chhoti Chaupar',
      'badi-chaupar': 'Badi Chaupar',
    },
    lines: [
      {
        id: 'pink',
        name: 'Pink Line',
        colour: '#D6457A',
        stops: [
          ['mansarovar', 0],
          ['new-aatish-market', 1.1],
          ['vivek-vihar', 2.3],
          ['shyam-nagar', 3.3],
          ['ram-nagar', 4.4],
          ['civil-lines', 5.7],
          ['railway-station', 7.2],
          ['sindhi-camp', 8.3],
          ['chandpole', 9.7],
          ['chhoti-chaupar', 10.9],
          ['badi-chaupar', 11.9],
        ],
      },
    ],
    fares: [
      [2, 6],
      [4, 8],
      [6, 10],
      [8, 12],
      [10, 14],
      [12, 16],
      [Infinity, 18],
    ],
  },
];

export const metroNetworkById = (networkId: string) => METRO_NETWORKS.find((n) => n.id === networkId);

export const metroNetworkForSlug = (slug: string) => METRO_NETWORKS.find((n) => n.slug === slug);

// Cabs -----------------------------------------------------------------------------------

/** [kind, name, approximate road distance from the destination's centre in km]. */
export type CabHub = readonly [kind: Exclude<CabPlaceKind, 'city_centre' | 'attraction'>, name: string, km: number];

/** Arrival points cabs are commonly booked from, for every destination. */
export const CAB_HUBS: Record<string, CabHub[]> = {
  delhi: [['airport', 'Indira Gandhi International Airport', 16], ['railway_station', 'New Delhi Railway Station', 3]],
  agra: [['railway_station', 'Agra Cantt Railway Station', 6], ['bus_station', 'Idgah Bus Stand', 5]],
  varanasi: [['airport', 'Lal Bahadur Shastri International Airport', 25], ['railway_station', 'Varanasi Junction', 4]],
  rishikesh: [['airport', 'Dehradun Airport (Jolly Grant)', 20], ['bus_station', 'Rishikesh ISBT', 2]],
  'leh-ladakh': [['airport', 'Kushok Bakula Rimpochee Airport', 4]],
  manali: [['airport', 'Bhuntar Airport (Kullu)', 50], ['bus_station', 'Manali Bus Stand', 1]],
  'spiti-valley': [['bus_station', 'Kaza Bus Stand', 1]],
  amritsar: [['airport', 'Sri Guru Ram Dass Jee International Airport', 11], ['railway_station', 'Amritsar Junction', 2]],
  khajuraho: [['airport', 'Khajuraho Airport', 5], ['railway_station', 'Khajuraho Railway Station', 8]],
  'valley-of-flowers': [['bus_station', 'Govindghat', 14]],
  jaipur: [['airport', 'Jaipur International Airport', 12], ['railway_station', 'Jaipur Junction', 3]],
  udaipur: [['airport', 'Maharana Pratap Airport', 22], ['railway_station', 'Udaipur City Railway Station', 4]],
  jaisalmer: [['railway_station', 'Jaisalmer Railway Station', 3], ['airport', 'Jaisalmer Airport', 13]],
  jodhpur: [['airport', 'Jodhpur Airport', 5], ['railway_station', 'Jodhpur Junction', 2]],
  ranthambore: [['railway_station', 'Sawai Madhopur Railway Station', 10]],
  mumbai: [['airport', 'Chhatrapati Shivaji Maharaj International Airport', 22], ['railway_station', 'Chhatrapati Shivaji Maharaj Terminus', 3]],
  goa: [['airport', 'Goa International Airport, Dabolim', 25], ['airport', 'Manohar International Airport, Mopa', 35], ['railway_station', 'Madgaon Railway Station', 30]],
  'rann-of-kutch': [['railway_station', 'Bhuj Railway Station', 70], ['bus_station', 'Bhuj Bus Station', 70]],
  'ajanta-ellora': [['airport', 'Chhatrapati Sambhajinagar Airport', 35], ['railway_station', 'Chhatrapati Sambhajinagar Railway Station', 30]],
  lonar: [['bus_station', 'Lonar Bus Stand', 2]],
  gir: [['railway_station', 'Junagadh Junction', 60], ['railway_station', 'Sasan Gir Railway Station', 1]],
  alappuzha: [['airport', 'Cochin International Airport', 85], ['railway_station', 'Alappuzha Railway Station', 4]],
  munnar: [['airport', 'Cochin International Airport', 110], ['bus_station', 'Munnar Bus Stand', 1]],
  kochi: [['airport', 'Cochin International Airport', 30], ['railway_station', 'Ernakulam Junction', 3], ['jetty', 'Fort Kochi Jetty', 12]],
  hampi: [['railway_station', 'Hosapete Junction', 13], ['bus_station', 'Hosapete Bus Stand', 13]],
  mysuru: [['railway_station', 'Mysuru Junction', 2], ['airport', 'Mysuru Airport', 12]],
  coorg: [['bus_station', 'Madikeri Bus Stand', 1], ['railway_station', 'Mysuru Junction', 120]],
  hyderabad: [['airport', 'Rajiv Gandhi International Airport', 30], ['railway_station', 'Secunderabad Junction', 8], ['railway_station', 'Hyderabad Deccan (Nampally)', 2]],
  warangal: [['railway_station', 'Warangal Railway Station', 3], ['railway_station', 'Kazipet Junction', 10]],
  madurai: [['airport', 'Madurai Airport', 12], ['railway_station', 'Madurai Junction', 1]],
  thanjavur: [['airport', 'Tiruchirappalli International Airport', 60], ['railway_station', 'Thanjavur Junction', 2]],
  mahabalipuram: [['airport', 'Chennai International Airport', 55], ['bus_station', 'Mamallapuram Bus Stand', 1]],
  puducherry: [['airport', 'Chennai International Airport', 150], ['railway_station', 'Puducherry Railway Station', 2]],
  gandikota: [['railway_station', 'Kadapa Railway Station', 85], ['bus_station', 'Jammalamadugu Bus Stand', 15]],
  'andaman-islands': [['airport', 'Veer Savarkar International Airport', 4], ['jetty', 'Haddo Wharf', 3]],
  kolkata: [['airport', 'Netaji Subhas Chandra Bose International Airport', 17], ['railway_station', 'Howrah Station', 5], ['railway_station', 'Sealdah Station', 3]],
  darjeeling: [['airport', 'Bagdogra Airport', 70], ['railway_station', 'New Jalpaiguri Junction', 75]],
  gangtok: [['airport', 'Pakyong Airport', 30], ['airport', 'Bagdogra Airport', 125]],
  meghalaya: [['airport', 'Shillong Airport (Umroi)', 45], ['airport', 'Lokpriya Gopinath Bordoloi International Airport', 130]],
  kaziranga: [['airport', 'Jorhat Airport', 90], ['railway_station', 'Furkating Junction', 75]],
  ziro: [['railway_station', 'Naharlagun Railway Station', 110]],
  majuli: [['jetty', 'Kamalabari Ghat', 10], ['airport', 'Jorhat Airport', 60]],
  'puri-konark': [['railway_station', 'Puri Railway Station', 35], ['airport', 'Biju Patnaik International Airport', 60]],
  'bodh-gaya': [['airport', 'Gaya Airport', 8], ['railway_station', 'Gaya Junction', 14]],
};

export interface CabVehicleDef {
  type: Extract<TransportVehicleType, 'auto' | 'hatchback' | 'sedan' | 'suv'>;
  seats: number;
  airConditioned: boolean;
  /** Sample tariff: flag-down rupees, rupees per km and minimum fare. */
  base: number;
  perKm: number;
  minimum: number;
  /** Longest ride offered, in km. */
  maxKm: number;
}

export const CAB_VEHICLES: CabVehicleDef[] = [
  { type: 'auto', seats: 3, airConditioned: false, base: 30, perKm: 17, minimum: 60, maxKm: 20 },
  { type: 'hatchback', seats: 4, airConditioned: true, base: 100, perKm: 16, minimum: 300, maxKm: 400 },
  { type: 'sedan', seats: 4, airConditioned: true, base: 120, perKm: 19, minimum: 400, maxKm: 600 },
  { type: 'suv', seats: 6, airConditioned: true, base: 180, perKm: 25, minimum: 600, maxKm: 600 },
];

/** Pre-booked rides only: the soonest pickup, and how far ahead a ride can be booked. */
export const CAB_MIN_NOTICE_MINUTES = 120;
export const CAB_MAX_DAYS_AHEAD = 90;

/** Airlines and bus operators publish schedules this far ahead. */
export const SCHEDULE_HORIZON_DAYS = 90;

/** Metro tickets can be bought for today or the next few days. */
export const METRO_MAX_DAYS_AHEAD = 7;
